export const WORKING_HOURS_PER_WEEK = 42;

export const WEEKS_IN_MONTH = 4;

export const MONTHS_IN_YEAR = 12;

export const WORKING_HOURS_PER_MONTH = WORKING_HOURS_PER_WEEK * WEEKS_IN_MONTH;

export const WORKING_HOURS_PER_YEAR = WORKING_HOURS_PER_MONTH * MONTHS_IN_YEAR;

export const MILLISECONDS_IN_SECOND = 1_000;

export const SECONDS_IN_MINUTE = 60;

export const MINUTES_IN_HOUR = 60;

export const MILLISECONDS_IN_HOUR = MINUTES_IN_HOUR * SECONDS_IN_MINUTE * MILLISECONDS_IN_SECOND;
